In [3]:
import os
import json
import pandas as pd

In [7]:
def get_average_recall(model,type="node"):
    sum_recall = 0
    sum_precision = 0
    sum_f1 = 0
    total_file = 0
    path = f"./uiuc_diagram_evaluater/eval_output/{model}"
    for i in os.listdir(path):
        if i.endswith(".json"):
            with open (path + "/" + i, "r") as f:
                data = json.load(f)
                scores = data[f'{type}_alignment']['scores']
                sum_recall+= scores['recall']
                sum_precision+= scores['precision']
                sum_f1 += scores['f1']
                total_file+=1
    return {"precision": sum_precision/total_file, "recall": sum_recall/total_file, "f1": sum_f1/total_file}

In [9]:
node_output = {"claude":0, "gpt4o":0,"gpt5":0}
for m in list(node_output.keys()):
    node_output[m] = get_average_recall(m)

In [10]:
path_output = {"claude":0,"gpt4o":0,"gpt5":0}
for m in list(path_output.keys()):
    path_output[m] = get_average_recall(m,type="path")

#### node alignment average scores

In [11]:
pd.DataFrame(node_output)

             claude     gpt4o      gpt5
precision  0.371926  0.512698  0.365154
recall     0.605106  0.500232  0.476899
f1         0.438057  0.479234  0.391502

#### path alignment average scores

In [12]:
pd.DataFrame(path_output)

             claude     gpt4o      gpt5
precision  0.432273  0.463287  0.470338
recall     0.167564  0.111991  0.168315
f1         0.222897  0.168355  0.226197